export const ALL_MOCK_PRODUCTS = [
  // WATCHES (10)
  { _id: 'w1', id: 'w1', name: 'Elite Chrono X', description: 'Precision engineered luxury watch with sapphire glass. Features a high-grade stainless steel case and a genuine leather strap.', price: 2400, category: 'Watches', brand: 'Elite', stock: 12, images: [{ url: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=500', publicId: 'w1' }], ratings: { average: 4.9, count: 150 }, isFeatured: true, isActive: true },
  { _id: 'w2', id: 'w2', name: 'Sport Master', description: 'Rugged smartwatch with GPS and heart rate monitoring. Perfect for outdoor enthusiasts and professional athletes.', price: 450, category: 'Watches', brand: 'Active', stock: 25, images: [{ url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500', publicId: 'w2' }], ratings: { average: 4.7, count: 88 }, isFeatured: false, isActive: true },
  { _id: 'w3', id: 'w3', name: 'Classic Gold', description: '18k gold plated vintage style timepiece. A timeless accessory for formal occasions.', price: 1800, category: 'Watches', brand: 'Vintage', stock: 8, images: [{ url: 'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=500', publicId: 'w3' }], ratings: { average: 4.8, count: 42 }, isFeatured: true, isActive: true },
  { _id: 'w4', id: 'w4', name: 'Stealth Black', description: 'Matte black minimalist watch for daily wear. Features a durable silicone strap and water resistance.', price: 299, category: 'Watches', brand: 'Minimal', stock: 50, images: [{ url: 'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=500', publicId: 'w4' }], ratings: { average: 4.5, count: 210 }, isFeatured: false, isActive: true },
  { _id: 'w5', id: 'w5', name: 'Aviator Pro', description: 'Professional pilot watch with dual time zone and slide rule bezel.', price: 950, category: 'Watches', brand: 'SkyHigh', stock: 15, images: [{ url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=500', publicId: 'w5' }], ratings: { average: 4.6, count: 75 }, isFeatured: false, isActive: true },
  { _id: 'w6', id: 'w6', name: 'Diver Depth', description: 'Water resistant up to 300m with luminous dial and ceramic bezel.', price: 1200, category: 'Watches', brand: 'Marine', stock: 10, images: [{ url: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=500', publicId: 'w6' }], ratings: { average: 4.9, count: 64 }, isFeatured: false, isActive: true },
  { _id: 'w7', id: 'w7', name: 'Urban Slim', description: 'Ultra-thin profile watch for professional settings. Fits perfectly under a shirt cuff.', price: 350, category: 'Watches', brand: 'Urban', stock: 30, images: [{ url: 'https://images.unsplash.com/photo-1508685096489-7aac2968395d?w=500', publicId: 'w7' }], ratings: { average: 4.4, count: 120 }, isFeatured: false, isActive: true },
  { _id: 'w8', id: 'w8', name: 'Legacy Automatic', description: 'Self-winding mechanical watch with open heart dial showing the movement.', price: 3200, category: 'Watches', brand: 'Heritage', stock: 5, images: [{ url: 'https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=500', publicId: 'w8' }], ratings: { average: 5.0, count: 12 }, isFeatured: true, isActive: true },
  { _id: 'w9', id: 'w9', name: 'Solar Charge', description: 'Sustainable solar-powered watch with 6 month power reserve and date function.', price: 550, category: 'Watches', brand: 'EcoTime', stock: 20, images: [{ url: 'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=500', publicId: 'w9' }], ratings: { average: 4.6, count: 95 }, isFeatured: false, isActive: true },
  { _id: 'w10', id: 'w10', name: 'Titanium Edge', description: 'Lightweight aerospace titanium casing and bracelet with brushed finish.', price: 1500, category: 'Watches', brand: 'TechTime', stock: 14, images: [{ url: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500', publicId: 'w10' }], ratings: { average: 4.8, count: 58 }, isFeatured: false, isActive: true },

  // AUDIO (10)
  { _id: 'a1', id: 'a1', name: 'Studio Pro Wireless', description: 'Professional grade studio headphones with Bluetooth 5.2 and 40h battery life.', price: 399, category: 'Audio', brand: 'Sonic', stock: 40, images: [{ url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500', publicId: 'a1' }], ratings: { average: 4.9, count: 320 }, isFeatured: true, isActive: true },
  { _id: 'a2', id: 'a2', name: 'Bass Boom Speaker', description: 'Portable waterproof speaker with deep bass and RGB lighting. IP67 rated.', price: 149, category: 'Audio', brand: 'Boom', stock: 60, images: [{ url: 'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=500', publicId: 'a2' }], ratings: { average: 4.6, count: 185 }, isFeatured: false, isActive: true },
  { _id: 'a3', id: 'a3', name: 'QuietFlow ANC', description: 'Industry leading active noise cancellation earbuds with transparency mode.', price: 249, category: 'Audio', brand: 'Flow', stock: 35, images: [{ url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500', publicId: 'a3' }], ratings: { average: 4.8, count: 245 }, isFeatured: true, isActive: true },
  { _id: 'a4', id: 'a4', name: 'Retro Vinyl Player', description: 'Modern turntable with built-in speakers, Bluetooth, and USB recording.', price: 299, category: 'Audio', brand: 'Groove', stock: 15, images: [{ url: 'https://images.unsplash.com/photo-1539375665275-f9ad415ef9ac?w=500', publicId: 'a4' }], ratings: { average: 4.7, count: 56 }, isFeatured: false, isActive: true },
  { _id: 'a5', id: 'a5', name: 'Podcaster Mic', description: 'XLR/USB condenser microphone for crystal clear audio recording and streaming.', price: 199, category: 'Audio', brand: 'Voice', stock: 25, images: [{ url: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=500', publicId: 'a5' }], ratings: { average: 4.8, count: 110 }, isFeatured: false, isActive: true },
  { _id: 'a6', id: 'a6', name: 'Sport Buds', description: 'Sweatproof wireless earbuds with secure ear hooks and 8h play time.', price: 99, category: 'Audio', brand: 'FitBeat', stock: 100, images: [{ url: 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=500', publicId: 'a6' }], ratings: { average: 4.3, count: 420 }, isFeatured: false, isActive: true },
  { _id: 'a7', id: 'a7', name: 'Cinema Bar 5.1', description: 'Surround sound bar with wireless subwoofer and Dolby Atmos support.', price: 599, category: 'Audio', brand: 'Vision', stock: 12, images: [{ url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=500', publicId: 'a7' }], ratings: { average: 4.7, count: 88 }, isFeatured: false, isActive: true },
  { _id: 'a8', id: 'a8', name: 'Hi-Fi Tower', description: 'Audiophile grade floor standing speakers with 3-way crossover system.', price: 1400, category: 'Audio', brand: 'LuxeAudio', stock: 6, images: [{ url: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=500', publicId: 'a8' }], ratings: { average: 5.0, count: 15 }, isFeatured: true, isActive: true },
  { _id: 'a9', id: 'a9', name: 'Compact Mini Speaker', description: 'Pocket sized Bluetooth speaker with 12h battery and built-in mic.', price: 49, category: 'Audio', brand: 'Nano', stock: 150, images: [{ url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500', publicId: 'a9' }], ratings: { average: 4.4, count: 560 }, isFeatured: false, isActive: true },
  { _id: 'a10', id: 'a10', name: 'Gold Series Over-Ear', description: 'Limited edition gold-accented reference headphones for critical listening.', price: 799, category: 'Audio', brand: 'Elite', stock: 10, images: [{ url: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500', publicId: 'a10' }], ratings: { average: 4.9, count: 42 }, isFeatured: false, isActive: true },

  // GADGETS (10)
  { _id: 'g1', id: 'g1', name: 'Smart Hub Max', description: 'Central controller for all your smart home devices with 10" display.', price: 229, category: 'Gadgets', brand: 'TechHome', stock: 30, images: [{ url: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=500', publicId: 'g1' }], ratings: { average: 4.7, count: 156 }, isFeatured: true, isActive: true },
  { _id: 'g2', id: 'g2', name: 'Drone Vision X', description: '4K camera drone with GPS, obstacle avoidance and 30m flight time.', price: 899, category: 'Gadgets', brand: 'SkyEye', stock: 15, images: [{ url: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500', publicId: 'g2' }], ratings: { average: 4.8, count: 92 }, isFeatured: true, isActive: true },
  { _id: 'g3', id: 'g3', name: 'VR Explorer', description: 'Standalone virtual reality headset with 4K resolution and 256GB storage.', price: 499, category: 'Gadgets', brand: 'Vista', stock: 20, images: [{ url: 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=500', publicId: 'g3' }], ratings: { average: 4.6, count: 210 }, isFeatured: false, isActive: true },
  { _id: 'g4', id: 'g4', name: 'PowerWall 20k', description: 'High capacity 20,000mAh portable power bank with 65W PD fast charging.', price: 79, category: 'Gadgets', brand: 'Juice', stock: 80, images: [{ url: 'https://images.unsplash.com/photo-1609091839311-d536801027d3?w=500', publicId: 'g4' }], ratings: { average: 4.5, count: 540 }, isFeatured: false, isActive: true },
  { _id: 'g5', id: 'g5', name: 'Laser Projector 4K', description: 'Ultra short throw 4K laser projector with 2500 ANSI lumens.', price: 2499, category: 'Gadgets', brand: 'Vision', stock: 8, images: [{ url: 'https://images.unsplash.com/photo-1535016120720-40c646bebbbb?w=500', publicId: 'g5' }], ratings: { average: 4.9, count: 34 }, isFeatured: true, isActive: true },
  { _id: 'g6', id: 'g6', name: 'Smart Garden', description: 'Indoor herb garden with automated watering, nutrition and LED lighting.', price: 129, category: 'Gadgets', brand: 'GreenTech', stock: 45, images: [{ url: 'https://images.unsplash.com/photo-1585336261022-69c66d117f6c?w=500', publicId: 'g6' }], ratings: { average: 4.4, count: 188 }, isFeatured: false, isActive: true },
  { _id: 'g7', id: 'g7', name: 'Mechanical Keypad', description: 'Wireless mechanical keypad with RGB and hot-swappable switches.', price: 119, category: 'Gadgets', brand: 'Click', stock: 55, images: [{ url: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=500', publicId: 'g7' }], ratings: { average: 4.7, count: 76 }, isFeatured: false, isActive: true },
  { _id: 'g8', id: 'g8', name: 'Security Cam Pro', description: 'AI powered 2K security camera with night vision and two-way audio.', price: 159, category: 'Gadgets', brand: 'Guard', stock: 100, images: [{ url: 'https://images.unsplash.com/photo-1557862921-37829c790f19?w=500', publicId: 'g8' }], ratings: { average: 4.6, count: 312 }, isFeatured: false, isActive: true },
  { _id: 'g9', id: 'g9', name: 'Health Ring', description: 'Titanium smart ring that tracks heart rate, SpO2, and sleep quality.', price: 299, category: 'Gadgets', brand: 'Vitality', stock: 40, images: [{ url: 'https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=500', publicId: 'g9' }], ratings: { average: 4.5, count: 89 }, isFeatured: false, isActive: true },
  { _id: 'g10', id: 'g10', name: 'Air Purifier Max', description: 'Medical grade HEPA 13 filter with smart app control.', price: 349, category: 'Gadgets', brand: 'PureAir', stock: 35, images: [{ url: 'https://images.unsplash.com/photo-1585338923907-74220377e03f?w=500', publicId: 'g10' }], ratings: { average: 4.8, count: 124 }, isFeatured: false, isActive: true },

  // ACCESSORIES (10)
  { _id: 'acc1', id: 'acc1', name: 'Leather Tech Folio', description: 'Handcrafted premium leather organizer for your daily tech essentials.', price: 145, category: 'Accessories', brand: 'Craft', stock: 50, images: [{ url: 'https://images.unsplash.com/photo-1512331283953-19967202267a?w=500', publicId: 'acc1' }], ratings: { average: 4.8, count: 142 }, isFeatured: true, isActive: true },
  { _id: 'acc2', id: 'acc2', name: 'Urban Backpack', description: 'Sleek weatherproof 20L backpack with padded laptop protection.', price: 129, category: 'Accessories', brand: 'Urban', stock: 75, images: [{ url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500', publicId: 'acc2' }], ratings: { average: 4.7, count: 230 }, isFeatured: true, isActive: true },
  { _id: 'acc3', id: 'acc3', name: 'Silk Sleep Mask', description: 'Luxury 22 momme mulberry silk mask for total blackout sleep.', price: 35, category: 'Accessories', brand: 'Cloud', stock: 200, images: [{ url: 'https://images.unsplash.com/photo-1582260127242-6e21625902bc?w=500', publicId: 'acc3' }], ratings: { average: 4.9, count: 450 }, isFeatured: false, isActive: true },
  { _id: 'acc4', id: 'acc4', name: 'MagSafe Wallet', description: 'Full-grain leather MagSafe compatible wallet with RFID shielding.', price: 59, category: 'Accessories', brand: 'Elite', stock: 150, images: [{ url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=500', publicId: 'acc4' }], ratings: { average: 4.6, count: 310 }, isFeatured: false, isActive: true },
  { _id: 'acc5', id: 'acc5', name: 'Titanium Key Loop', description: 'CNC machined titanium key loop with quick release mechanism.', price: 45, category: 'Accessories', brand: 'Minimal', stock: 300, images: [{ url: 'https://images.unsplash.com/photo-1559564484-e48b3e040ff4?w=500', publicId: 'acc5' }], ratings: { average: 4.7, count: 88 }, isFeatured: false, isActive: true },
  { _id: 'acc6', id: 'acc6', name: 'Wool Laptop Sleeve', description: 'Durable and soft wool felt sleeve with magnetic closure.', price: 65, category: 'Accessories', brand: 'EcoCase', stock: 90, images: [{ url: 'https://images.unsplash.com/photo-1544333346-64e3fe13b194?w=500', publicId: 'acc6' }], ratings: { average: 4.8, count: 124 }, isFeatured: false, isActive: true },
  { _id: 'acc7', id: 'acc7', name: 'Travel Tech Kit', description: 'Padded organizer for chargers, adapters and small electronics.', price: 39, category: 'Accessories', brand: 'Traveler', stock: 180, images: [{ url: 'https://images.unsplash.com/photo-1530177150700-84cd9a3b059b?w=500', publicId: 'acc7' }], ratings: { average: 4.5, count: 560 }, isFeatured: false, isActive: true },
  { _id: 'acc8', id: 'acc8', name: 'Carbon Fiber Pen', description: 'Professional writing instrument with real carbon fiber barrel.', price: 85, category: 'Accessories', brand: 'Edge', stock: 45, images: [{ url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=500', publicId: 'acc8' }], ratings: { average: 4.9, count: 72 }, isFeatured: false, isActive: true },
  { _id: 'acc9', id: 'acc9', name: 'Copper Bottle', description: 'Sleek copper bottle designed for wellness and style.', price: 49, category: 'Accessories', brand: 'Vital', stock: 120, images: [{ url: 'https://images.unsplash.com/photo-1602143399827-7211bf3ad910?w=500', publicId: 'acc9' }], ratings: { average: 4.7, count: 312 }, isFeatured: false, isActive: true },
  { _id: 'acc10', id: 'acc10', name: 'Suede Desk Mat', description: 'Waterproof recycled suede desk mat with non-slip base.', price: 75, category: 'Accessories', brand: 'Studio', stock: 65, images: [{ url: 'https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=500', publicId: 'acc10' }], ratings: { average: 4.8, count: 96 }, isFeatured: false, isActive: true },
];
